spring.application.name=backend

jwt.secret=your-256-bit-secret-key-here-make-it-at-least-32-bytes-long

#postgres connection
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres_teamapp
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update